---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
heartrate <- read.csv("data/heartrate.csv")
```

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate %>% 
  select(patient, a) %>% 
  ggplot(aes(x=patient, y=a)) +
    geom_col()
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate %>% 
  pivot_longer(-patient,
               names_to= "drug",
               values_to = "heartrate") %>% 
  ggplot(aes(x=drug, y=heartrate))+ geom_boxplot(alpha=0.7) #alpha makes it more transparent
```
```{r}
sharktank <- read.csv("Shark Tank US dataset.csv")
sharktank %>% 
  select(Startup.Name, Total.Deal.Amount) %>% 
  arrange(desc(Total.Deal.Amount))
```

```{r}
sharktank %>% 
  filter(Startup.Name == "EcoFlower") %>% 
  select(Startup.Name, Total.Deal.Amount, Total.Deal.Equity, )
```

```{r}
glimpse(sharktank)
```

