---
title: "Lab_5_warmup"
output: html_document
date: "2023-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. Load the bison data.
```{r}
bison <- readr::read_csv("data/bison.csv")
```

2. What are the dimesions and structure of the data?
```{r}
dim(bison)
```
```{r}
str(bison)
```

3. We are only interested in code, sex, weight, year of birth. Restrict the data to these variables and store the dataframe as a new object.
```{r}
bison_code_sex_weight_yearofbirth <- select(bison, animal_code, animal_sex, animal_weight, animal_yob)
bison_code_sex_weight_yearofbirth
```

4. Pull out the animals born between 1980-1990.
```{r}
bison_code_sex_weight_yearofbirth_1980 <- filter(bison_code_sex_weight_yearofbirth, animal_yob>=1980)
bison_code_sex_weight_yearofbirth_1980_1990 <- filter(bison_code_sex_weight_yearofbirth, animal_yob<=1990)
bison_code_sex_weight_yearofbirth_1980_1990
```

5. How many male and female bison are represented between 1980-1990?
```{r}
table(bison_code_sex_weight_yearofbirth_1980_1990$animal_sex)
```

Between 1980-1990, were males or females larger on average?
```{r}
bison_code_sex_weight_yearofbirth_1980_1990_males <- filter(bison_code_sex_weight_yearofbirth_1980_1990, animal_sex == "M")
bison_code_sex_weight_yearofbirth_1980_1990_males
```
```{r}
bison_code_sex_weight_yearofbirth_1980_1990_females <- filter(bison_code_sex_weight_yearofbirth_1980_1990, animal_sex == "F")
bison_code_sex_weight_yearofbirth_1980_1990_females
```
```{r}
mean(bison_code_sex_weight_yearofbirth_1980_1990_males$animal_weight)
```

```{r}
mean(bison_code_sex_weight_yearofbirth_1980_1990_females$animal_weight)
```

